#!/usr/bin/env bash
git clone https://github.com/Nekuskus/dotfiles

pushd /etc/nixos
mkdir ../nixos-backup
mv * ../nixos-backup
popd

cd dotfiles/nixos
ln -s . /etc/nixos
cp /etc/nixos-backup/hardware-configuration.nix /etc/nixos/hardware-configuration.nix
nixos-rebuild switch
unlink /etc/nixos

mv dotfiles /home/mi/dotfiles

# TODO: Separate post-install into smaller scripts for i3, bash, ...

cd /home/mi
ln -s dotfiles/scripts .local/bin
ln -s dotfiles/bash/.bashrc .bashrc
ln -s dotfiles/bash/.bash_profile .bash_profile
ln -s dotfiles/bash/.sshrc .ssh/rc

passwd mi


systemctl reboot
