#!/usr/bin/env bash
git clone https://github.com/Nekuskus/dotfiles

pushd /etc/nixos
mkdir ../nixos-backup
mv * ../nixos-backup
popd

cd dotfiles/nixos
ln -s . /etc/nixos
nixos-rebuild switch
unlink /etc/nixos

mv dotfiles /home/mi/dotfiles
passwd mi
