#!/usr/bin/env bash
pushd ~/dotfiles/nixos/
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch \
  &> nixos-switch.log \
  || (cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
if [ -n "$1" ]; then
  git commit -am "$gen $1"
else
  git commit -am "$gen"
fi
popd
